#!/bin/bash

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    echo "Add current directory and subdirectories to tar.gz archive"
    echo "Use "`basename $0`" [-nc]"
    echo "[-nc] - add only content current directory (and subdirectories)."
    echo
    echo "Archive name == current directory name."
    echo "Archive will be created to up-directory."
    exit 0
fi

CURDIR=`pwd`

if [ "$CURDIR" == "/" ]; then
    echo "Oh, no! It's root directory!"
    exit 1
fi

DIRNAME=`basename $CURDIR`
ARHNAME="../"$DIRNAME".tar.gz"


if [ "$1" == "-nc" ]; then
    tar -czvf $ARHNAME "."
else
    tar -czvf $ARHNAME "../"$DIRNAME
fi



