#!/bin/bash

#check parameters and print help
if [ -z "$1" ]; then
    echo "Use " `basename $0` "<binary_file>"
    exit 1
fi
if [[ "$1" == "-h" ]]; then
    echo "Use " `basename $0` "<binary_file>"
    exit 1
fi
if [[ "$1" == "--help" ]]; then
    echo "Use " `basename $0` "<binary_file>"
    exit 1
fi


cat $1|hexdump -e '27/1 "%02X " "\n"' >$1.dump