#!/bin/bash

IFS_=$IFS
IFS=$'\n'
for TMPSTRING in $(cat "demotable.txt")
do
    eval $(echo "$TMPSTRING"|awk -F "," '{print "LOGIN=" sq $1 sq; 
    print "FULLNAME=" sq $2 sq; print "PHONE=" sq $3 sq; print"ROOM=" sq $4 sq;
    print "WORKTIME=" sq $5 sq}' sq="'")
    
    clear
    echo "Login: $LOGIN"
    echo "Full name: $FULLNAME"
    echo "Phone: $PHONE"
    echo "Room: $ROOM"
    echo "Work time: $WORKTIME"
    echo "Press any key to display next user..."
    read -n 1 -s -r
done
IFS=$IFS_